name: Create prerelease

defaults:
  run:
    shell: powershell

on:
  push:
    paths: 
      - 'Scripts/**'
      - 'Tools/**'
    branches: [ dev ]

jobs:
  new-prerelease:
    name: Create prerelease
    if: "!contains(github.event.head_commit.message, '[no release]')"
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build scripts 
        id: build
        shell: powershell
        run: |
          ./build.ps1 -Version dev
          $filename = "mslab_dev-$((Get-Date -Format "yyyyMMdd")).zip"
          mv ./Release.zip $filename
          echo "filename=$filename" >> $env:GITHUB_OUTPUT
      - name: Create new release
        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: dev
          name: dev branch preview
          generate_release_notes: true
          prerelease: true
          files: |
            ${{ steps.build.outputs.filename }}
            Output/Tools/*.ps1
#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "dev"
#          prerelease: true
#          title: "dev branch preview"
#          files: |
#            ${{ steps.build.outputs.filename }}
